import React, { useState, useMemo, useEffect } from 'react';
import { ScoredHotel } from '../types';
import { X, ExternalLink, Calendar, CheckCircle, ShieldCheck, ArrowRight } from 'lucide-react';
import { AffiliateDeepLinker } from '../services/AffiliateDeepLinker';

interface BookingModalProps {
  hotel: ScoredHotel;
  interest: string;
  onClose: () => void;
  onConfirm: () => void;
}

const BookingModal: React.FC<BookingModalProps> = ({ hotel, interest, onClose, onConfirm }) => {
  const [isSuccess, setIsSuccess] = useState(false);
  const [isMobile, setIsMobile] = useState(false);

  // Detect Mobile Device on Mount
  useEffect(() => {
    const checkMobile = () => {
      const userAgent = typeof navigator === 'undefined' ? '' : navigator.userAgent;
      return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(userAgent);
    };
    setIsMobile(checkMobile());
  }, []);

  // MOCK DATA GENERATION FOR AFFILIATE LINK
  // In a real app, these would come from the user's search query state
  const bookingDates = useMemo(() => {
    const checkIn = new Date();
    checkIn.setDate(checkIn.getDate() + 14); // Default to 2 weeks from now
    
    const checkOut = new Date(checkIn);
    checkOut.setDate(checkOut.getDate() + 3); // 3 nights stay
    
    return { checkIn, checkOut };
  }, []);

  // Format for display
  const displayDateString = `${bookingDates.checkIn.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} - ${bookingDates.checkOut.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} (3 Nights)`;

  // Generate the link immediately
  const affiliateLink = useMemo(() => {
    // Check if it's a dynamic (simulated) hotel or a specific one from our mock DB
    const isDynamic = hotel.id.startsWith('dyn_');

    // STRATEGY:
    // 1. If it's a Dynamic Hotel (generated by algorithm), it doesn't exist on Booking.com.
    //    We send the user to a City Search for that city.
    // 2. If it's a Mock Data Hotel (e.g. Generator Berlin), it exists.
    //    We send the user to a search for "Hotel Name, City" to find that specific property.
    const searchQuery = isDynamic ? hotel.city : `${hotel.name}, ${hotel.city}`;

    return AffiliateDeepLinker.generateBookingLink(
      searchQuery,
      bookingDates.checkIn,
      bookingDates.checkOut,
      '123456', // YOUR MOCK AFFILIATE ID
      interest
    );
  }, [bookingDates, interest, hotel]);

  const handleBookingClick = () => {
    // CRITICAL FIX: Delay the state update. 
    // If we update React state immediately, the <a> tag is removed from the DOM 
    // instantly. Some browsers/OSs stop processing the 'href' navigation 
    // if the source element is destroyed during the event bubble phase.
    // This delay ensures the "Open in Booking.com" action completes first.
    setTimeout(() => {
      setIsSuccess(true);
    }, 1000);
  };

  return (
    <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4 backdrop-blur-sm animate-in fade-in duration-300">
      <div className="bg-white w-full max-w-md rounded-2xl shadow-2xl overflow-hidden animate-in zoom-in-95 duration-300 relative">
        
        {/* Header */}
        <div className="flex justify-between items-center p-5 border-b border-gray-100 bg-white sticky top-0 z-10">
          <h2 className="font-bold text-lg text-gray-900">
            {isSuccess ? 'Welcome Back!' : 'Complete Booking'}
          </h2>
          {!isSuccess && (
            <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-full transition-colors text-gray-500">
              <X size={20} />
            </button>
          )}
        </div>

        {/* Success State (Post-Redirect) */}
        {isSuccess ? (
          <div className="p-8 flex flex-col items-center text-center animate-in zoom-in duration-300">
            <div className="w-16 h-16 bg-green-100 text-green-600 rounded-full flex items-center justify-center mb-4 shadow-sm">
              <CheckCircle size={32} />
            </div>
            <h3 className="text-2xl font-extrabold text-gray-900 mb-2">Did you book it?</h3>
            <p className="text-gray-500 mb-6 text-sm">
              If you secured your spot at {hotel.name}, you can now join the {interest} lobby chat!
            </p>
            
            <button 
              onClick={onConfirm}
              className="w-full bg-brand-600 hover:bg-brand-700 text-white font-bold py-4 rounded-xl shadow-lg transition-colors mb-3"
            >
              Yes, I'm Booked - Join Lobby
            </button>
            <button 
              onClick={onClose}
              className="w-full bg-white text-gray-500 font-medium py-3 rounded-xl hover:bg-gray-50 transition-colors text-sm"
            >
              No, still looking
            </button>
          </div>
        ) : (
          /* Pre-Redirect State */
          <div>
            <div className="p-6 overflow-y-auto max-h-[70vh]">
              
              {/* Hotel Summary Card */}
              <div className="flex gap-4 mb-8 bg-gray-50 p-4 rounded-xl border border-gray-100">
                <img src={hotel.images[0]} alt={hotel.name} className="w-20 h-20 object-cover rounded-lg shadow-sm" />
                <div>
                  <h3 className="font-bold text-gray-900">{hotel.name}</h3>
                  <p className="text-sm text-gray-500 mb-2">{hotel.city}</p>
                  <div className="inline-flex items-center bg-brand-50 text-brand-700 text-[10px] font-bold px-2 py-1 rounded-md uppercase tracking-wide border border-brand-100">
                    <span className="w-1.5 h-1.5 bg-brand-500 rounded-full mr-1.5 animate-pulse"></span>
                    Joining {hotel.matchingGuestCount} {interest} Fans
                  </div>
                </div>
              </div>

              {/* Booking Details */}
              <div className="space-y-5 mb-8">
                <div>
                  <label className="block text-xs font-bold text-gray-500 mb-1.5 uppercase tracking-wider">Estimated Dates</label>
                  <div className="relative group">
                    <Calendar size={18} className="absolute left-3.5 top-3.5 text-gray-400 group-focus-within:text-brand-500 transition-colors" />
                    <input 
                      type="text" 
                      value={displayDateString} 
                      readOnly 
                      className="w-full bg-gray-50 border border-gray-200 text-gray-900 font-medium text-sm rounded-xl pl-10 pr-4 py-3 focus:outline-none cursor-not-allowed" 
                    />
                  </div>
                  <p className="text-[10px] text-gray-400 mt-1 ml-1">Dates can be adjusted on the partner site.</p>
                </div>
              </div>

              {/* Affiliate Notice */}
              <div className="bg-blue-50 border border-blue-100 rounded-lg p-3 flex items-start gap-3">
                <div className="bg-blue-100 p-1.5 rounded-full text-blue-600 mt-0.5">
                   <ExternalLink size={14} />
                </div>
                <div className="text-xs text-blue-800">
                  <span className="font-bold block mb-0.5">Booking via Partner</span>
                  To ensure the best price and secure payment, you will be redirected to Booking.com. 
                  {!isMobile && " This will open in a new tab."}
                </div>
              </div>
            </div>

            {/* Footer Action - SMART LINKING */}
            <div className="p-5 border-t border-gray-100 bg-gray-50 rounded-b-2xl">
              <a 
                href={affiliateLink}
                // LOGIC: 
                // Mobile: Target self (undefined) to allow Deep Linking to App without triggering "New Tab + App" bug.
                // Desktop: Target blank to keep VibeLobby open in background.
                target={isMobile ? undefined : "_blank"}
                rel={isMobile ? undefined : "noopener noreferrer"}
                onClick={handleBookingClick}
                className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-4 rounded-xl shadow-lg flex items-center justify-center transition-all transform active:scale-[0.98] hover:shadow-xl text-center cursor-pointer decoration-0"
              >
                <span className="flex items-center">
                   Book on Booking.com <ArrowRight size={18} className="ml-2" />
                </span>
              </a>
              <div className="flex items-center justify-center gap-1 text-[10px] text-gray-400 mt-3 font-medium uppercase tracking-wide">
                <ShieldCheck size={12} className="text-green-500" /> Official Partner • Best Price Guarantee
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default BookingModal;